### ISSUE TITLE
vLLM sometimes doesn't work when `PYTORCH_CUDA_ALLOC_CONF` is set to `expandable_segments:True`

### ISSUE THREAD

**Issue by chewong** [kaito-project/kaito#1077]
**Is your feature request related to a problem? Please describe.**

vLLM deployment crashed with the following error message:

![Image](https://github.com/user-attachments/assets/69329358-9efd-45c3-b459-4719f377a92f)

Found this from vLLM repository: https://github.com/vllm-project/vllm/issues/9046.

It works fine for tensor parallelism = 1 but anything >1 would crash vLLM.

**Describe the solution you'd like**

Remove the environment variable from vLLM deployment but not sure what effect it would have.

**Describe alternatives you've considered**

**Additional context**

**Comment by zhuangqh** [comment]
The main idea of adding this env was to reduce memory Fragments.

```yaml
apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-phi-4-mini
resource:
  instanceType: "Standard_NC12s_v3"
  labelSelector:
    matchLabels:
      apps: phi-4
inference:
  preset:
    name: phi-4-mini-instruct 
  config: "inference-params"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-params
data:
  inference_config.yaml: |
    # Maximum number of steps to find the max available seq len fitting in the GPU memory.
    max_probe_steps: 6

    vllm:
      cpu-offload-gb: 0
      gpu-memory-utilization: 0.95
      swap-space: 4
      max-model-len: 2048
```

I can successfully run this workspace with 2 tensor parallelism. In fact, we have a e2e test to cover this case.
Can you confirm how to reproduce this issue? do you run it on multi nodes?
