### ISSUE TITLE
cannot create service for workspace

### ISSUE THREAD

**Issue by zhuangqh** [kaito-project/kaito#725]
**Describe the bug**

workspace fails to be created with error:
```
I1125 09:50:07.591485       1 resources.go:25] "CreateService" service="default/workspace-phi-3.5-mini"
2024-11-25T09:50:08Z    ERROR   Reconciler error        {"controller": "workspace", "controllerGroup": "kaito.sh", "controllerKind": "Workspace", "Workspace": {"name":"workspace-phi-3.5-mini","namespace":"default"}, "namespace": "default", "name": "workspace-phi-3.5-mini", "reconcileID": "1afb4bb9-7e8a-4aa4-b5a4-dbd9ad45f392", "error": "Service \"workspace-phi-3.5-mini\" is invalid: metadata.name: Invalid value: \"workspace-phi-3.5-mini\": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')"}
```

**Steps To Reproduce**

create a workspace 
```
apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  name: workspace-phi-3.5-mini
resource:
  instanceType: "Standard_NC6s_v3"
  labelSelector:
    matchLabels:
      apps: phi-3
inference:
  preset:
    name: phi-3.5-mini
```

**Expected behavior**

**Logs**

**Environment**

- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Install tools:
- Others: 

**Additional context**

0.3.2 version
