### ISSUE TITLE
Add support for phi 4 preset

### ISSUE THREAD

**Issue by surajssd** [kaito-project/kaito#790]
**Describe the solution you'd like**

I would like to use a preset that deploys phi 4 model that was announced last week: https://techcommunity.microsoft.com/blog/aiplatformblog/introducing-phi-4-microsoft%E2%80%99s-newest-small-language-model-specializing-in-comple/4357090

Something like this:

```yaml
apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  name: workspace-phi-4
resource:
  instanceType: "Standard_NC6s_v3"
  labelSelector:
    matchLabels:
      apps: phi-4
inference:
  preset:
    name: phi-4
```
